# Generated by Django 3.1.14 on 2023-03-01 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_cover'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('privilegios_group', 'Can read all books')]},
        ),
    ]
